//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Output
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Output()
        {
            this.OutputInfoes = new HashSet<OutputInfo>();
        }
    
        public string ID { get; set; }
        public int IDCustomer { get; set; }
        public int IDUser { get; set; }
        public Nullable<int> IDPromotion { get; set; }
        public Nullable<System.DateTime> DateOutput { get; set; }
        public string Status { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
    }
}
